CREATE TABLE IF NOT EXISTS study_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  subject VARCHAR(100) NOT NULL,
  hours DECIMAL(5,2) NOT NULL,
  study_date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
