apiVersion: v1
kind: Secret
metadata:
  name: study-hours-secrets
  namespace: study-hours
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: studytracker
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppassword
  JWT_SECRET: supersecret_dev_change_me
  FLASK_SECRET_KEY: dev_secret_change_me
  SESSION_SECRET: dev_session_change_me
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: study-hours-config
  namespace: study-hours
data:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MONGO_URL: mongodb://mongo:27017
  MONGO_DB: studytracker
  AUTH_URL: http://auth-service:3000
  PORT_AUTH: "3000"
  PORT_ENTER: "5000"
  PORT_SHOW: "4000"
  RUN_EVERY_SECONDS: "10"
