apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-service
  namespace: study-hours
spec:
  replicas: 2
  selector:
    matchLabels:
      app: show-service
  template:
    metadata:
      labels:
        app: show-service
    spec:
      containers:
        - name: show-service
          image: 772161510099.dkr.ecr.us-west-2.amazonaws.com/show-service:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: study-hours-config
                  key: PORT_SHOW
            - name: AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: study-hours-config
                  key: AUTH_URL
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: study-hours-config
                  key: MONGO_URL
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: study-hours-config
                  key: MONGO_DB
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: study-hours-secrets
                  key: SESSION_SECRET
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: show-service
  namespace: study-hours
spec:
  type: LoadBalancer
  selector:
    app: show-service
  ports:
    - port: 80
      targetPort: 4000
